import {
  DEMO_COMPONENTS,
  DEMO_INCIDENTS,
  DEMO_LOCATIONS,
  DEMO_PEOPLE,
  DEMO_POLICIES,
  DEMO_TEAMS,
  DEMO_TERMS,
} from "../world";
import type { DemoNarrativeMap } from "./types";

const { margotChen, caseyTremblay, priyaSharma, rileyNguyen, morganEllis } =
  DEMO_PEOPLE;

/**
 * Audit and Accountability family narratives, excluding au-2 and au-6, which
 * are authored in ./featured.
 */
export function auditAccountabilityNarratives(): DemoNarrativeMap {
  return {
    "au-1": `${DEMO_POLICIES.audit} is owned by ${margotChen.name} and maintained jointly by ${caseyTremblay.name} and ${priyaSharma.name}. It defines the auditable-event catalog referenced under au-2, retention schedules, and escalation responsibilities for ${DEMO_TEAMS.acu}. The policy is reviewed annually and after any authorization package update, consistent with the review cadence set in ${DEMO_POLICIES.planning}.`,

    "au-3": `Audit records across ${DEMO_COMPONENTS.sgopCore.name}, ${DEMO_COMPONENTS.featherAuth.name}, ${DEMO_COMPONENTS.cims.name}, ${DEMO_COMPONENTS.deploymentApi.name}, and ${DEMO_COMPONENTS.nestWatch.name} capture a standardized timestamp, event type, source, outcome, and subject identity. ${caseyTremblay.name} maintains the shared record schema so that ${DEMO_TEAMS.acu} can correlate events across systems without per-tool translation.`,

    "au-3.1": `High-value events — coconut release approvals, ${DEMO_COMPONENTS.deploymentApi.name} tasking calls, and privileged logon — capture additional context beyond the au-3 baseline: session geolocation, device identifier, and the name of the approving official. This additional detail supports the correlation work described under au-6.3 and the after-action reviews required by ${DEMO_POLICIES.incidentResponse}.`,

    "au-4": `${DEMO_COMPONENTS.nestWatch.name} log storage is sized for 400 days of retention at current ingest volume, with an alert to ${caseyTremblay.name} at 80 percent capacity. The threshold was breached once, during ${DEMO_INCIDENTS.nestingSurge.name}, prompting temporary log rotation before additional capacity was provisioned.`,

    "au-5": `A logging-pipeline failure alerts ${DEMO_TEAMS.acu} immediately. If audit capture for ${DEMO_COMPONENTS.deploymentApi.name} is unavailable for more than ten minutes, ${DEMO_COMPONENTS.sgopCore.name} halts new tasking rather than proceed without an audit trail. ${caseyTremblay.name} owns the fail-secure runbook and tests it during each quarterly exercise.`,

    "au-6.1": `${DEMO_COMPONENTS.nestWatch.name} automatically correlates events from ${DEMO_COMPONENTS.featherAuth.name}, ${DEMO_COMPONENTS.cims.name}, and ${DEMO_COMPONENTS.deploymentApi.name} against defined correlation rules and opens a ticket for the watch floor when a rule matches, reducing reliance on manual cross-referencing during the daily au-6 review.`,

    "au-6.3": `Audit repositories from ${DEMO_COMPONENTS.honkNet.name}, ${DEMO_COMPONENTS.cims.name}, and Mobile Field Terminal sync logs are correlated centrally in ${DEMO_COMPONENTS.nestWatch.name} rather than reviewed system by system. This cross-repository correlation was used directly to reconstruct the ${DEMO_TERMS.coconutChainOfCustody} timeline during the ${DEMO_INCIDENTS.coconut2024.name} investigation.`,

    "au-7": `${DEMO_COMPONENTS.nestWatch.name} provides filtering and report-generation tools used by ${DEMO_TEAMS.acu} to reduce raw audit volume to actionable summaries. A standard weekly report goes to ${margotChen.name}; ad hoc queries support incident-response investigations without requiring direct access to the underlying storage.`,

    "au-7.1": `${DEMO_COMPONENTS.nestWatch.name} automatically runs a standing set of reduction queries — including privileged ${DEMO_COMPONENTS.cims.name} actions outside normal business hours — on a fixed schedule rather than requiring an analyst to construct the query manually each time. Results feed the au-6 daily review queue.`,

    "au-8": `All CGDS systems synchronize to an authoritative NTP source maintained by ${caseyTremblay.name}, who monitors for drift and alarms above one second of offset. Records generated by ${DEMO_COMPONENTS.rfc1149Gateway.name} during a ${DEMO_LOCATIONS.disasterRecoveryPond.name} activation are hand-logged with local time and reconciled against the authoritative clock once ${DEMO_COMPONENTS.honkNet.name} connectivity is restored.`,

    "au-9": `${DEMO_COMPONENTS.nestWatch.name} audit storage is write-once and restricted to ${DEMO_TEAMS.acu}. Any change to logging configuration proposed by ${rileyNguyen.name} requires a second approval from ${DEMO_TEAMS.acu} before it takes effect, preventing a single configuration change from silently altering what gets recorded.`,

    "au-9.4": `Administrative rights over the audit log store itself are held only by ${margotChen.name} and two senior ${DEMO_TEAMS.acu} analysts, distinct from the broader set of privileged operational users described under ac-6.5. This separation prevents day-to-day privileged users from being able to modify the record of their own actions.`,

    "au-11": `Audit records are retained 365 days online in ${DEMO_COMPONENTS.nestWatch.name} and seven years in the ${DEMO_COMPONENTS.backupRepo.name} for coconut custody and deployment-tasking records, per the schedule in ${DEMO_POLICIES.audit}. ${morganEllis.name} verifies archive integrity during the quarterly backup check described under cp-9.`,

    "au-12": `${DEMO_COMPONENTS.sgopCore.name}, ${DEMO_COMPONENTS.featherAuth.name}, ${DEMO_COMPONENTS.deploymentApi.name}, ${DEMO_COMPONENTS.cims.name}, and ${DEMO_COMPONENTS.nestWatch.name} generate records meeting the au-3 content requirements automatically at the component level. ${caseyTremblay.name} validates generation coverage during each configuration baseline review; a gap discovered in the badge-printer subsystem after the ${DEMO_INCIDENTS.printerSpool.name} was closed within the same review cycle.`,
  };
}
